jwt:
  time: 90000
  secret: hello-world
posco:
  name: 3기 2번째 config
  count: 20
  datasource:
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
spring:
  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:file:~/test
    username: test  # 사용자 이름 (로그인 시 사용)
    password: 1234  # 사용자 암호 (로그인 시 사용)