jwt:
  time: 1111
  secret: hello-world~
posco:
  name: 3기 3번째 config
  count: 20
  datasource:
    url: jdbc:mysql://localhost:?.?.?.?:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
spring:
  datasource:
    url: jdbc:mysql://localhost:?.?.?.?:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234