jwt:
  time: 90000
  secret: hello-world
posco:
  name: 3기 2번째 config
  count: 20
test:
  datasource:
    url: jdbc:mysql://localhost:?.?.?.?:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
    username: noh
    password: 1234